name: Compilation testing

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: mingw-w64-toolchain mingw-w64-x86_64-toolchain

    - shell: msys2 {0}
      run: make -C src -f WINDOWS_makefile

