name: Compilation testing

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - uses: msys2/setup-msys2@v2
      with:
        install: gfortran make
    -  run: make -C src -f WINDOWS_makefile

